export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_USER = 'GET_USER';

export const FILTER_USER = 'FILTER_USER';
export const ADD_USER = 'ADD_USER';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const ADD_USER_STATUS_FAILURE = 'ADD_USER_STATUS_FAILURE';
export const ADD_USER_STATUS_SUCCESS = 'ADD_USER_STATUS_SUCCESS';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';