export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_RESPONSE = 'GET_USERS_RESPONSE';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const FILTER_USER = 'FILTER_USER';
export const ADD_USER = 'ADD_USER';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';